#!/bin/sh

# Welcome to the thoughtbot laptop script!
# Be prepared to turn your laptop (or desktop, no haters here)
# into an awesome development machine.

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}

append_to_zshrc() {
  local text="$1" zshrc
  local skip_new_line="${2:-0}"

  if [ -w "$HOME/.zshrc.local" ]; then
    zshrc="$HOME/.zshrc.local"
  else
    zshrc="$HOME/.zshrc"
  fi

  if ! grep -Fqs "$text" "$zshrc"; then
    if [ "$skip_new_line" -eq 1 ]; then
      printf "%s\n" "$text" >> "$zshrc"
    else
      printf "\n%s\n" "$text" >> "$zshrc"
    fi
  fi
}

# shellcheck disable=SC2154
trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

if [ ! -d "$HOME/bin/" ]; then
  mkdir "$HOME/bin"
fi

if [ ! -f "$HOME/.zshrc" ]; then
  touch "$HOME/.zshrc"
fi

# shellcheck disable=SC2016
append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'

HOMEBREW_PREFIX="/usr/local"

if [ -d "$HOMEBREW_PREFIX" ]; then
  if ! [ -r "$HOMEBREW_PREFIX" ]; then
    sudo chown -R "$LOGNAME:admin" /usr/local
  fi
else
  sudo mkdir "$HOMEBREW_PREFIX"
  sudo chflags norestricted "$HOMEBREW_PREFIX"
  sudo chown -R "$LOGNAME:admin" "$HOMEBREW_PREFIX"
fi

update_shell() {
  local shell_path;
  shell_path="$(which zsh)"

  fancy_echo "Changing your shell to zsh ..."
  if ! grep "$shell_path" /etc/shells > /dev/null 2>&1 ; then
    fancy_echo "Adding '$shell_path' to /etc/shells"
    sudo sh -c "echo $shell_path >> /etc/shells"
  fi
  chsh -s "$shell_path"
}

case "$SHELL" in
  */zsh)
    if [ "$(which zsh)" != '/usr/local/bin/zsh' ] ; then
      update_shell
    fi
    ;;
  *)
    update_shell
    ;;
esac


if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."
    curl -fsS \
      'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby

    append_to_zshrc '# recommended by brew doctor'

    # shellcheck disable=SC2016
    append_to_zshrc 'export PATH="/usr/local/bin:$PATH"' 1

    export PATH="/usr/local/bin:$PATH"
fi

if brew list | grep -Fq brew-cask; then
  fancy_echo "Uninstalling old Homebrew-Cask ..."
  brew uninstall --force brew-cask
fi

fancy_echo "Updating Homebrew formulae ..."
brew update
brew bundle --file=- <<EOF
tap "thoughtbot/formulae"
tap "homebrew/services"

# Unix
brew "ansible"
brew "azure-cli"
brew "bash"
brew "certbot"
brew "consul"
brew "doctl"
brew "git"
brew "git-flow"
brew "go"
brew "gox"
brew "jq"
brew "yq"
brew "kubernetes-cli"
brew "kubernetes-helm"
brew "maven"
brew "netcat"
brew "minisign"
brew "nomad"
brew "openssl"
brew "pv"
brew "python"
brew "python3"
brew "python@2"
brew "rcm"
brew "readline"
brew "terminal-notifier"
brew "terraform"
brew "the_silver_searcher"
brew "tig"
brew "tree"
brew "vault"
brew "vim"
brew "watchman"
brew "zsh"
brew "plantuml"
brew "lnav"

brew "figlet"
brew "ffmpeg"
brew "flac"
brew "flyway"
brew "kubectx"
brew "ssh-copy-id"
brew "dos2unix"
brew "wget"
brew "parquet-tools"

# GitHub
brew "hub"

# nvm / node
brew "nvm"
#export NVM_DIR=~/.nvm
#source $(brew --prefix nvm)/nvm.sh
#source ~/.bash_profile


# Homebrew-Cask
tap "caskroom/cask"
brew "mas"

# Cask apps
cask "visual-studio-code"
cask "macdown"
cask "vlc"
cask "typora"
cask "zoomus"
cask "paw"
cask "telegram"
cask "meld"
cask "firefox"
cask "intellij-idea"
cask "datagrip"
cask "webstorm"
cask "atom"
cask "iterm2"
cask "ngrok"
cask "minikube"
cask "spectacle"
cask "vagrant"
cask "vagrant-manager"
cask "virtualbox"
cask "knockknock"
cask "syncthing"
cask "obs"
cask "keybase"
cask "arduino"
cask "0xed"
#cask "flux"
cask "balenaetcher"
cask "alfred2"


# mas apps
mas "Simplenote", id: 692867256
mas "NordVPN IKE", id: 1116599239 
mas "LastPass", id: 926036361
#mas "Growl", id: 467939042
#mas "HardwareGrowler", id: 475260933
#mas "Big Mean Folder Machine 2", id: 402440280
#mas "ForkLift", id: 412448059
mas "Flycut", id: 442160987
#mas "Xcode", id: 497799835
mas "Slack", id: 803453959

EOF

if [ -f "$HOME/.laptop.local" ]; then
  fancy_echo "Running your customizations from ~/.laptop.local ..."
  # shellcheck disable=SC1090
  . "$HOME/.laptop.local"
fi
